---
include:
  - board: seeeduino_xiao_ble
    shield: narsil
  - board: nice_nano_v2
    shield: anduril
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
