# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "seeeduino_xiao_ble" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: seeeduino_xiao_ble
#     shield: reviung41
#
---
include:

#  - board: rpi_pico
#    shield: void9
    
#  - board: seeeduino_xiao_ble
 #   shield: narsil_left rgbled_adapter
#  - board: seeeduino_xiao_ble
 #   shield: narsil_right rgbled_adapter
    
 #- board: seeeduino_xiao_ble
 #  shield: klein_left rgbled_adapter
 #- board: seeeduino_xiao_ble
 #  shield: klein_right rgbled_adapter
    
 # - board: seeeduino_xiao_ble
 #  shield: settings_reset
    
 - board: nice_nano_v2
   shield: settings_reset
   
 - board: nice_nano_v2
   shield: anduril
   snippet: studio-rpc-usb-uart
    
